export const GET_PRODUCTS = "GET_PRODUCTS";
export const ALL_CATEGORY = "ALL_CATEGORY";
export const ADD_PRODUCTS = "ADD_PRODUCTS";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const REGISTER_USER = "REGISTER_USER";
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
