[
    {
        id:1,
        name:"2x1 pantalon",
        img:"akjdalkdjakld.jpg",
        OfferProduct:[
            {
                quantity:2,
                idProduct:            {
                    id:2,
                    name:pantalon,
                    img:"imagenpantalon.jpg",
                    description:"dkadkljkjdahd jdhajdalhwjh fajkhfjkhdhw kjahdkjawhdawkdjl",
                    category:[
                        {
                            id:1,
                            name:"pantalon",
                        }
                    ],
                    genero:[
                        {
                            id:2,
                            name:"masculino"
                        }
                    ],
                    talle:[
                        {
                            id:3,
                            name:"XL",
                            stock:7
                        }
                    ],
                    marca:[
                        {
                            id:4,
                            name:"adidas"
                        }
                    ],
                    price:1000,
    
                }
            },
            {
                quantity:2,
                idProduct:{
                    id:2,
                    name:pantalon,
                    img:"imagenpantalon.jpg",
                    description:"dkadkljkjdahd jdhajdalhwjh fajkhfjkhdhw kjahdkjawhdawkdjl",
                    category:[
                        {
                            id:1,
                            name:"pantalon",
                        }
                    ],
                    genero:[
                        {
                            id:2,
                            name:"masculino"
                        }
                    ],
                    talle:[
                        {
                            id:3,
                            name:"XL",
                            stock:7
                        }
                    ],
                    marca:[
                        {
                            id:4,
                            name:"adidas"
                        }
                    ],
                    price:1000,
    
                }
            }
        ],
        price:1500
    },
]

[
    {
        "id":1,
        "name":"producto1",
        "description":"lorem",
        "image":"URL",
        "marca":"Adidas",
        "genero":"sin genero",//3 opciones
        "stock":12,
        "colors":[{"id":"negro"},{"id":"azul"},{"id":"blanco"}],//relacion de tablas
        "talla":[{"id":"XL"},{"id":"M"},{"id":"S"}],//relacion de tablas
        "price":123
        
    }
]
{   
    idCart:1,
    products:[
        {quantity:1,
        product:{
            id:1,
            name:name
            }
        },
        {quantity:3,
            product:{
                id:6,
                name:name
            }
        },
        {quantity:1,
            product:{
                id:4,
                name:name
            }
        },
    ],
    offers:[
        {quantity:1,
        product:{
            id:1,
            name:name
            }
        },
        {quantity:3,
            product:{
                id:6,
                name:name
            }
        },
        {quantity:1,
            product:{
                id:4,
                name:name
            }
        },
    ]
}        


